/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradingIndexRouteImport } from './routes/trading/index'
import { Route as TradingOptimizeRouteImport } from './routes/trading/optimize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingIndexRoute = TradingIndexRouteImport.update({
  id: '/trading/',
  path: '/trading/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingOptimizeRoute = TradingOptimizeRouteImport.update({
  id: '/trading/optimize',
  path: '/trading/optimize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trading/optimize': typeof TradingOptimizeRoute
  '/trading/': typeof TradingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trading/optimize': typeof TradingOptimizeRoute
  '/trading': typeof TradingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trading/optimize': typeof TradingOptimizeRoute
  '/trading/': typeof TradingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trading/optimize' | '/trading/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trading/optimize' | '/trading'
  id: '__root__' | '/' | '/trading/optimize' | '/trading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TradingOptimizeRoute: typeof TradingOptimizeRoute
  TradingIndexRoute: typeof TradingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/': {
      id: '/trading/'
      path: '/trading'
      fullPath: '/trading/'
      preLoaderRoute: typeof TradingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading/optimize': {
      id: '/trading/optimize'
      path: '/trading/optimize'
      fullPath: '/trading/optimize'
      preLoaderRoute: typeof TradingOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TradingOptimizeRoute: TradingOptimizeRoute,
  TradingIndexRoute: TradingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
